/*
Project: Pizza Sales Analysis
Database: MySQL
Description:
This file contains SQL queries used to analyze pizza sales data,
answer business questions, and generate insights related to revenue,
orders, and product performance.
*/
create database pizza_db;
use pizza_db;
create table orders(
order_id int primary key,
order_date date,
order_time time);

create table order_details(
order_details_id int primary key,
order_id int, 
pizza_id varchar(50),
quantity int,
 FOREIGN KEY (order_id) REFERENCES orders(order_id));

create table pizza(
pizza_id varchar(50) primary key,
pizza_type_id varchar(50),
size varchar(3),
price decimal(15,5));

create table pizza_types(
pizza_type_id varchar(50),
name varchar(50),
category varchar(50),
ingredients text);

SELECT * FROM order_details;
SELECT * FROM orders;
SELECT * FROM pizza;
SELECT * FROM pizza_types;

-- 1. What pizzas are available and how much do they cost?
select pizza_type_id,size, price
from pizza;

-- 2. What are the pizza categories and ingredients?
select name, category, ingredients
from pizza_types;

-- 3. Which pizzas cost more than $15?
select *
from pizza
where price>15;

-- 4. What pizzas fall under the vegetarian category?
select *
from pizza_types
where category='vegetarian';

-- 5. What is the most expensive pizza?
select *
from pizza
order by price desc
limit 1;

-- 6. What are the details of each order along with pizza prices?
select od.order_details_id,od.order_id,od.pizza_id,od.quantity,pz.price
from order_details as od
join pizza as pz
on od.pizza_id=pz.pizza_id;

-- 7. Which pizza was ordered and what category does it belong to?
SELECT od.order_id, od.pizza_id, pt.category
FROM order_details od
JOIN pizza p 
ON od.pizza_id = p.pizza_id
JOIN pizza_types pt 
ON p.pizza_type_id = pt.pizza_type_id;

-- 8. On which dates were pizzas ordered and what pizzas were ordered?
select o.order_date,pt.name
from orders as o
join order_details as od
on o.order_id=od.order_id
join pizza p
on p.pizza_id=od.pizza_id
join pizza_types as pt
on p.pizza_type_id=pt.pizza_type_id;

-- 9. What is the total quantity of pizzas sold?
select sum(quantity) as Total_Pizza_Sold
from order_details;

-- 10. What is the total revenue generated from pizza sales?
select sum(od.quantity*p.price) as total_revenue
from order_details as od
join pizza as p
on od.pizza_id=p.pizza_id;

-- 11. How many orders were placed on each day?
select order_date, count(*) as total_orders
from orders
group by order_date;

-- 12. How much revenue did each pizza generate?
select od.pizza_id, sum(od.quantity*p.price) as Revenue
from order_details as od
join pizza as p
on od.pizza_id=p.pizza_id
group by od.pizza_id;

-- 13. How much revenue was generated by each pizza category?
select pt.category, sum(od.quantity*p.price) as Revenue
from order_details as od
join pizza as p
on od.pizza_id=p.pizza_id
join pizza_types as pt
on pt.pizza_type_id=p.pizza_type_id
group by pt.category;

-- 14. Which pizza categories generated revenue greater than $30?
select pt.category, sum(od.quantity*p.price) as Revenue
from order_details as od
join pizza as p
on od.pizza_id=p.pizza_id
join pizza_types as pt
on pt.pizza_type_id=p.pizza_type_id
group by pt.category
having revenue>30;

-- 15. Which pizzas were ordered more than once?
select pizza_id,sum(quantity) as total_quantity
from order_details
group by pizza_id
having total_quantity>1;

-- 16. How do pizzas rank based on total revenue?
select pizza_id,sum(quantity*price) as total_revenue,
rank() over (order by sum(quantity*price)desc) as revenue_rank
from order_details as od
join pizza as p
using (pizza_id)
group by pizza_id;

-- 17. How do daily orders accumulate over time?
select order_date, count(*) as daily_orders, sum(count(*)) 
over (order by order_date) as running_total
from orders
group by order_date;

-- 18. Which pizza category is the top-selling by revenue?
with category_rev as (select pt.category, sum(od.quantity * p.price) as revenue
from order_details od
join pizza p ON od.pizza_id = p.pizza_id
join pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
group by pt.category
)
select *
from category_rev
order by revenue desc
limit 1;








